CREATE TABLE aws_access_keys (
    aws_key_id VARCHAR(255),
    aws_key_secret VARCHAR(255)
);

INSERT INTO aws_access_keys VALUES( 'AKIAIOSFODNN7EXAMPLE', 'wJalrXUtnFEMI/K7MDENG/bPxRfiC1EXAMPLEKEY');
INSERT INTO aws_access_keys VALUES( 'ASIAY34FZKBNKMUTVV7A', 'wJalrXUtnFEMI/K7MDENG/bPxRfiC2EXAMPLEKEY');
INSERT INTO aws_access_keys VALUES( 'AKIARJFBAG3EGHFG2FPN', 'wJalrXUtnFEMI/K7MDENG/bPxRfiC3EXAMPLEKEY');

