namespace: test

architecture: x64

remote_debug: false

kernel: 
  version: 6.3.5
  disable_kaslr: true
  disable_smap: true
  disable_smep: true
  disable_pti: true
  quiet: true
  boot_args: ""

root_filesystem: 
  busy_box: 
    uid: 1000
    version: 1.36.1
    includes:
      - from: examples/test/module/kmod.ko
        to: /
    init_extra: "insmod /kmod.ko"
  
