namespace: test

architecture: x64

remote_debug: false

kernel: 
  version: 6.3.5
  disable_kaslr: true
  disable_smap: true
  disable_smep: true
  disable_pti: true
  quiet: true
  boot_args: ""
  
  

root_filesystem: 
  busy_box: 1.36.1
