version: "3"
services:

  mongo:
    image: mongo:latest
    ports:
      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_DATABASE: "csc842"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
      - ./docker/mongo-init:/docker-entrypoint-initdb.d/:ro
      - type: volume
        source: mongodb
        target: /data
    command: mongod
 
volumes:
  mongodb: